### ISSUE TITLE
Change Lucent License to MIT. Lucent is Non-Free.

### ISSUE THREAD

**Issue by ergpopler** [aligrudi/neatroff_make#17]
The Lucent license is considered a non-free software license [1].
I assume part of the troff stuff is licensed under the Lucent 1.02 license is because you used code from Plan9.
Nokia bought Bell labs, and gave the copyright of Plan9 to the Plan9 Foundation [2][3].
The Plan9 foundation relicensed all the code to the MIT license [3].
What this means, is that the plan9 code here is eligible to be used under the MIT License.
If I am understanding correctly, your contributions are also under the Lucent license. 
README says this stuff is ISC Licensed, so I assume you will have no issue with relicensing the parts of troff that you wrote, as the other parts of troff are now eligible under both Lucent or MIT. 
You should remove the Lucent bullcrap!
```
[theo@thinkpad ~/.local/src/neatroff_make]$ cat troff/NOTICE 
Copyright (C) 2003, Lucent Technologies Inc. and others. All Rights Reserved.
Copyright (C) 2011-2012, Ali Gholami Rudi

The original code as distributed by Lucent and the second copyright holder's
contributions are under Lucent Public License, Version 1.02.
```
Should be changed to, Copyright whatever, but under the MIT License.

References:
1. https://www.gnu.org/philosophy/plan-nine.html
2. https://www.bell-labs.com/institute/blog/plan-9-bell-labs-cyberspace/
3. https://p9f.org/about.html

**Comment by aligrudi** [comment]
Thank you very much.  A patch is very much appreciated.

**Comment by ergpopler** [comment]
> Thank you very much. A patch is very much appreciated.

https://repo.or.cz/troff/idk.git/patch/741da8e222031cfc45e56d1182704ef59271065b?hp=dbad9a7632595b111f56a4193da0b151a2dd37f4

**Comment by aligrudi** [comment]
ergpopler ***@***.***> wrote:
> > Thank you very much. A patch is very much appreciated.
> 
> https://repo.or.cz/troff/idk.git/patch/741da8e222031cfc45e56d1182704ef59271065b?hp=dbad9a7632595b111f56a4193da0b151a2dd37f4

Thank you very much.  Applied.

	Ali

**Comment by ergpopler** [comment]
Great. Closing issue.
