### ISSUE TITLE
Consider migrating `repo.or.cz/troff` fork to GitHub

### ISSUE THREAD

**Issue by Alhadis** [aligrudi/neatroff_make#23]
This repository's [sources](https://github.com/aligrudi/neatroff_make/blob/3fbdda4ef1ca14b19eedfd3c58ef99c3f59dd289/Makefile#L27-L32) are all hosted on GitHub, save one — a fork of Plan9's `pic` and `tbl` ports for Linux hosted at [`repo.or.cz/troff.git`](https://repo.or.cz/troff.git). This is problematic because `repo.or.cz`'s uptime is rather… volatile.

Several times I've attempted to `git clone` a repository hosted there, only to be met with connection failure. These periods of downtime can last between a few hours or several days, with the last crash prompting me to [make a fork](https://github.com/Cutlery-Drawer/neatroff_mods) in order to have a stable source from which to install `neatpic` and `neattbl`. I'd strongly prefer to use a canonical source instead.

Which brings me “neatly” along to my second point: a few months ago, I finished work on a [Homebrew formula](https://docs.brew.sh/Formula-Cookbook) for installing Neatroff on macOS (via the [`alhadis/troff` tap](https://github.com/Alhadis/homebrew-troff/blob/master/Formula/neatroff.rb)). It includes a subroutine for checking each of `neatroff_make`'s constituents for updates, something which was non-trivial to implement. Much of the complexity stemmed from having to support an obscure host in addition to GitHub.com, the latter can efficiently query multiple APIs in [a single payload](https://github.com/Alhadis/homebrew-troff/blob/c92363feeddb6fd3d927fc330ba1e3e7fe7d65c9/Formula/neatroff.rb#L287-L306).

@aligrudi, would you be willing to move [your fork](https://repo.or.cz/troff.git/tree/refs/heads/neat) over to GitHub? This would make everybody's lives much easier. 😀 Thank you!

**Comment by aligrudi** [comment]
John Gardner ***@***.***> wrote:
> Which brings me “neatly” along to my second point: a few months ago,
> I finished work on a [Homebrew
> formula](https://docs.brew.sh/Formula-Cookbook) for installing
> Neatroff on macOS (via the [`alhadis/troff`
> tap](https://github.com/Alhadis/homebrew-troff/blob/master/Formula/neatroff.rb)).
> It includes a subroutine for checking each of `neatroff make`'s
> constituents for updates, something which was non-trivial to
> implement. Much of the complexity stemmed from having to support an
> obscure host in addition to GitHub.com, the latter can efficiently
> query multiple APIs in [a single
> payload](https://github.com/Alhadis/homebrew-troff/blob/c92363feeddb6fd3d927fc330ba1e3e7fe7d65c9/Formula/neatroff.rb#L287-L306).

Interesting.

> @aligrudi, would you be willing to move [your
> fork](https://repo.or.cz/troff.git/tree/refs/heads/neat) over to
> GitHub? This would make everybody's lives much easier. 😀 Thank you!

OK.  I will do so later today.

Thanks,
Ali

**Comment by Alhadis** [comment]
> OK.  I will do so later today.

Any update?

**Comment by aligrudi** [comment]
John Gardner ***@***.***> wrote:
> > OK.  I will do so later today.
> 
> Any update?

Sorry for the long delay.  I was waiting for a suggestion for its name,
and it was forgotten altogether (I finally chose troffp9...).

Please report if there is any problem.

Thanks,
Ali

**Comment by Alhadis** [comment]
Perfect, thank you so much! 😀 I've updated the [package description](https://github.com/Alhadis/homebrew-troff/commit/4b64721c2f03e4785922a0ccb4ff2e25bd2c560f) accordingly.

**Comment by aligrudi** [comment]
John Gardner ***@***.***> wrote:
> @aligrudi, would you be willing to move [your
> fork](https://repo.or.cz/troff.git/tree/refs/heads/neat) over to
> GitHub? This would make everybody's lives much easier.

Any suggestions for the name of the repository?

troff_plan9linux
plan9troff_linux
p9troff_linux
..

Thanks,
Ali

**Comment by Alhadis** [comment]
> Any suggestions for the name of the repository?

`troffp9` works for me (and it's already [in-use](https://github.com/Alhadis/homebrew-troff/blob/5f7d8b4951f321aee3aafe359fcfecd69e8ea1b4/Formula/neatroff.rb#L146) by the Homebrew formula used to install Neatroff).

Thanks again!
