### ISSUE TITLE
return type defaults to ‘int’ [-Wimplicit-int] error when compiling

### ISSUE THREAD

**Issue by fernandohv3279** [aligrudi/neatroff_make#28]
Hello, I followed the instructions on the readme.
`make init` is okay but when I do 
`make neat` I get errors like this:
```
picl.c:3012:1: error: return type defaults to ‘int’ [-Wimplicit-int]
 3012 | yylook(void){
      | ^~~~~~
```
How can I fix this?
Thank you!

**Comment by aligrudi** [comment]
Hello.

fernandohv3279 ***@***.***> wrote:
> Hello, I followed the instructions on the readme.
> `make init` is okay but when I do 
> `make neat` I get errors like this:
> `picl.c:3012:1: error: return type defaults to ‘int’ [-Wimplicit-int]
>  3012 | yylook(void){
>           | ^~~~~~`
> How can I fix this?

Does adding -Wimplicit-int to CFLAGS help?

	Ali

**Comment by fernandohv3279** [comment]
I added that flag but it didn't help, however I got it to compile with -fpermissive, probably not the best way but it works :)
Thank you very much!
