### ISSUE TITLE
possibly an error around the setup of the pic preprocessor

### ISSUE THREAD

**Issue by nbehrnd** [aligrudi/neatroff_make#29]
With neatroff_make (as provided by commit [7cf23e4](https://github.com/aligrudi/neatroff_make/commit/7cf23e411527a8e85c6fda689523f90b5f03a235) by February 4, 2023), I attempt the installation of neatroff in an instance of Linux Debian 13/trixie with GNU Make 4.3 and gs/ghostscript version 10.03.1.

The log back to the terminal reports a couple of warnings and errors; I presume the later might be the reason why the installation eventually fails (i.e., the subsequent run of `make` in the demo folder yields a pdf of a blank page).  Reporting only the lines around the keyword `error`, see 

```shell
cc -c -Wall -O2 picy.c
picy.c: In function ‘yyparse’:
picy.c:741:1: warning: label ‘yyerrlab’ defined but not used [-Wunused-label]
  741 | yyerrlab:
      | ^~~~~~~~
cc -c -Wall -O2 picl.c
picl.c:65:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   65 | yylex(void){
      | ^~~~~
picl.c: In function ‘yylex’:
picl.c:83:1: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   83 | if(yywrap()) return(0); break;
      | ^~
picl.c:83:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   83 | if(yywrap()) return(0); break;
      |                         ^~~~~
picl.c:81:1: warning: label ‘yyfussy’ defined but not used [-Wunused-label]
   81 | yyfussy: switch(nstr){
      | ^~~~~~~
picl.c:66:22: warning: unused variable ‘yyprevious’ [-Wunused-variable]
   66 | int nstr; extern int yyprevious;
      |                      ^~~~~~~~~~
picl.c: At top level:
picl.c:2087:55: warning: missing braces around initializer [-Wmissing-braces]
 2087 | struct yywork { YYTYPE verify, advance; } yycrank[] = {
      |                                                       ^
 2088 | 0,0,    0,0,    3,17,   0,0,
      | {  }    {  }    {   }   {  }
 2089 | 5,59,   0,0,    0,0,    0,0,
      | {   }   {  }    {  }    {  }
 2090 | 0,0,    0,0,    3,18,   3,19,
      | {  }    {  }    {   }   {   }
 2091 | 5,59,   5,60,   0,0,    0,0,
      | {   }   {   }   {  }    {  }
 2092 | 0,0,    0,0,    0,0,    0,0,

[...]

2395 | 522,522,        522,522,        522,522,        522,522,
      | {      }        {      }        {      }        {      }
 2396 | 522,522,        522,522,        0,0,    0,0,
      | {      }        {      }        {  }    {  }
 2397 | 0,0};
      | {  }
picl.c:2398:25: warning: missing braces around initializer [-Wmissing-braces]
 2398 | struct yysvf yysvec[] = {
      |                         ^
 2399 | 0,      0,      0,
      | {                }
 2400 | yycrank+0,      0,              0,
      | {                                }
 2401 | yycrank+0,      0,              0,
      | {                                }

[...]

 2939 | yycrank+0,      0,              yyvstop+1053,
      | {                                           }
 2940 | yycrank+0,      yysvec+31,      yyvstop+1055,
      | {                                           }
 2941 | yycrank+0,      yysvec+31,      yyvstop+1058,
      | {                                           }
 2942 | 0,      0,      0};
      | {                }
picl.c:2999: warning: ignoring ‘#pragma lib ’ [-Wunknown-pragmas]
 2999 | #pragma lib     "libl.a"
picl.c:3012:1: error: return type defaults to ‘int’ [-Wimplicit-int]
 3012 | yylook(void){
      | ^~~~~~
picl.c:3158:1: error: return type defaults to ‘int’ [-Wimplicit-int]
 3158 | yyback(int *p, int m)
      | ^~~~~~
picl.c:3169:1: error: return type defaults to ‘int’ [-Wimplicit-int]
 3169 | yyinput(void){
      | ^~~~~~~
make[1]: *** [Makefile:10: picl.o] Error 1
make[1]: Leaving directory '/home/test/Desktop/home2neatroff/neatroff_make/troff/pic'
make: *** [Makefile:56: comp] Error 2
```
The subsequent test run in the folder `demo` looks like this:

```shell
$ make
Generating demo.ps
/bin/sh: 1: /home/test/Desktop/home2neatroff/neatroff_make/demo/../troff/pic/pic: not found
/bin/sh: 1: /home/test/Desktop/home2neatroff/neatroff_make/demo/../troff/tbl/tbl: not found
neatroff: cannot open device utf
Generating demo.pdf
Error: /undefined in done
Operand stack:
Execution stack:   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1949   1   3   %oparray_pop   1948   1   3   %oparray_pop   1933   1   3   %oparray_pop   1803   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:   --dict:755/1123(ro)(G)--   --dict:0/20(G)--   --dict:85/200(L)--
Current allocation mode is local
Current file position is 54
GPL Ghostscript 10.03.1: Unrecoverable error, exit code 1
make: *** [Makefile:38: demo.pdf] Error 1
rm demo.ps
```

Within reach of the particular user account equally is an installation of groff (incl. pdfgroff, geqn, pic, etc.) provided as version 1.23.0 by the repositories of Debian; this one is functional.

**Comment by nbehrnd** [comment]
To check if the top level Makefile is able to collect all data necessary for the subsequent installation of neatroff, I run [shellcheck](https://tracker.debian.org/pkg/shellcheck) version 0.10.0 as provided by Linux Debian 13/trixie.  Its analysis reports

```shell
$ shellcheck Makefile 

In Makefile line 11:
PWD = $${PWD}
        ^-- SC1083 (warning): This { is literal. Check expression (missing ;/\n?) or quote it.
            ^-- SC1083 (warning): This } is literal. Check expression (missing ;/\n?) or quote it.


In Makefile line 28:
	@test -d neatroff || git clone https://github.com/aligrudi/neatroff.git
        ^-- SC1073 (error): Couldn't parse this bats @test. Fix to allow more checks.
              ^-- SC1072 (error):  Fix any mentioned problems and try again.

For more information:
  https://www.shellcheck.net/wiki/SC1083 -- This { is literal. Check expressi...
  https://www.shellcheck.net/wiki/SC1072 --  Fix any mentioned problems and t...
  https://www.shellcheck.net/wiki/SC1073 -- Couldn't parse this bats @test. F...
```

**Comment by aligrudi** [comment]
nbehrnd ***@***.***> wrote:
> To check if the top level Makefile is able to collect all data
> necessary for the subsequent installation of neatroff, I run
> [shellcheck](https://tracker.debian.org/pkg/shellcheck) version 0.10.0
> as provided by Linux Debian 13/trixie.  Its analysis reports

Thanks.  Neatroff uses the old tbl and pic preprocessors,
which use c89-style function definitions that omit the return
type.  Please see if adding the -std=c89 option of GCC fixes
the problem:

$ cd troff/pic
$ CFLAGS=-std=c89
$ make clean all

If it does not fix it, please try the following patch:

diff --git a/pic/picl.c b/pic/picl.c
index e68c399..0521e96 100644
--- a/pic/picl.c
+++ b/pic/picl.c
@@ -62,7 +62,7 @@ char	cbuf[CBUFLEN];
 int	c, clen, cflag, delim;
 int	ifsw	= 0;	/* 1 if if statement in progress */
 #define YYNEWLINE 10
-yylex(void){
+int yylex(void){
 int nstr; extern int yyprevious;
 yyin = stdin;
 yyout = stdout;
@@ -3009,7 +3009,7 @@ int yyprevious = YYNEWLINE;
 # ifdef LEXDEBUG
 extern void allprint(int);
 # endif
-yylook(void){
+int yylook(void){
 	struct yysvf *yystate, **lsp;
 	struct yywork *yyt;
 	struct yysvf *yyz;
@@ -3155,7 +3155,7 @@ yylook(void){
 # endif
 		}
 	}
-yyback(int *p, int m)
+int yyback(int *p, int m)
 {
 if (p==0) return(0);
 while (*p)
@@ -3166,7 +3166,7 @@ while (*p)
 return(0);
 }
 	/* the following are only used in the lex library */
-yyinput(void){
+int yyinput(void){
 	return(input());
 }
 void

Does this fix the problem?

Thanks,
Ali

**Comment by nbehrnd** [comment]
Affirmative, the suggestion resolves the issue.

Out of precaution, I started with a pristine checkout from GitHub.  After the `make init`, I  replaced the very first line `CFLAGS = -Wall -O2` by `CFLAGS = -std=c89` in file `/neatroff_make/troff/pic/Makefile`.  At level of the top Makefile, the continuation

```shell
$ make neat
$ cd demo
$ make
```

indeed generated multiple non-empty pdf files.  No additional edits were necessary to reach this encouraging result.

Side note: `/demo/neatroff.ms`, line 45 includes a (partial) code switch with (Danish, Norsk, Swedish, German, Czech).  This were a plausible reason for `Nomenklature` (with _k_) instead of presumed intention of `Nomenclature` (with _c_).  Thank you very much.
