### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by awkfan77** [aligrudi/neatroff_make#4]
Please add a licence.

**Comment by aligrudi** [comment]
awkfan77 <notifications@github.com> wrote:
> Please add a licence.

The main part of neatroff_make is the tmac directory, for which
there exists tmac/NOTICE.  The programs include their own
license (all of them are under ISC), included in one of their
files containing main().

If it is necessary I shall add a note in README for everything
else.

	Ali

**Comment by awkfan77** [comment]
> If it is necessary I shall add a note in README for everything else.

`soin/soin.c`, the docs and the makefiles don't have licences, I think you should add a note in the README.

> The programs include their own license (all of them are under ISC), included in one of their files containing main().

Including the licence as a comment in just one source file per program doesn't make it that clear that it applies to the whole program, maybe you should add a note saying that it applies to the whole program.
